In [1]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv("data/bulls_data.csv")
df.head()

,Season,Lg,Team,W,L,W/L%,Finish,SRS,Unnamed: 8,Pace,Rel Pace,ORtg,Rel ORtg,DRtg,Rel DRtg,Unnamed: 15,Playoffs,Coaches,Top WS
0,2025-26,NBA,Chicago Bulls,27,38,0.415,4th of 5,-4.08,NaN,101.7,2.3,113.2,-2.2,117.3,1.9,NaN,NaN,B. Donovan (27-38),T. Jones (4.2)
1,2024-25,NBA,Chicago Bulls,39,43,0.476,5th of 5,-1.83,NaN,102.8,4.0,114.1,-0.4,115.6,1.1,NaN,NaN,B. Donovan (39-43),N. Vučević (7.3)
2,2023-24,NBA,Chicago Bulls,39,43,0.476,4th of 5,-1.77,NaN,96.3,-2.2,114.9,-0.4,116.3,1.0,NaN,NaN,B. Donovan (39-43),D. DeRozan (9.2)
3,2022-23,NBA,Chicago Bulls,40,42,0.488,3rd of 5,1.37,NaN,98.5,-0.6,113.5,-1.3,112.2,-2.6,NaN,NaN,B. Donovan (40-42),D. DeRozan (8.5)
4,2021-22,NBA,Chicago Bulls*,46,36,0.561,2nd of 5,-0.38,NaN,98.3,0.1,113.2,1.2,113.6,1.6,NaN,Lost E. Conf. 1st Rnd.,B. Donovan (46-36),D. DeRozan (8.8)

In [8]:
# convert season to integer, removing hyphen-"next year" part

df["Season"] = df["Season"].apply(lambda x: int(x.split("-")[0]))
df.head()

,Season,Lg,Team,W,L,W/L%,Finish,SRS,Unnamed: 8,Pace,Rel Pace,ORtg,Rel ORtg,DRtg,Rel DRtg,Unnamed: 15,Playoffs,Coaches,Top WS
0,2025,NBA,Chicago Bulls,27,38,0.415,4th of 5,-4.08,NaN,101.7,2.3,113.2,-2.2,117.3,1.9,NaN,NaN,B. Donovan (27-38),T. Jones (4.2)
1,2024,NBA,Chicago Bulls,39,43,0.476,5th of 5,-1.83,NaN,102.8,4.0,114.1,-0.4,115.6,1.1,NaN,NaN,B. Donovan (39-43),N. Vučević (7.3)
2,2023,NBA,Chicago Bulls,39,43,0.476,4th of 5,-1.77,NaN,96.3,-2.2,114.9,-0.4,116.3,1.0,NaN,NaN,B. Donovan (39-43),D. DeRozan (9.2)
3,2022,NBA,Chicago Bulls,40,42,0.488,3rd of 5,1.37,NaN,98.5,-0.6,113.5,-1.3,112.2,-2.6,NaN,NaN,B. Donovan (40-42),D. DeRozan (8.5)
4,2021,NBA,Chicago Bulls*,46,36,0.561,2nd of 5,-0.38,NaN,98.3,0.1,113.2,1.2,113.6,1.6,NaN,Lost E. Conf. 1st Rnd.,B. Donovan (46-36),D. DeRozan (8.8)

In [ ]:
# drop "Unnamed: 8", "Unnamed: 15" column, which is empty
df.drop(columns=["Unnamed: 8", "Unnamed: 15"], inplace=True)
df.head()

# despite NAs in the Playoffs column, we leave them be to show a "missed" playoffs season.

,Season,Lg,Team,W,L,W/L%,Finish,SRS,Pace,Rel Pace,ORtg,Rel ORtg,DRtg,Rel DRtg,Playoffs,Coaches,Top WS
0,2025,NBA,Chicago Bulls,27,38,0.415,4th of 5,-4.08,101.7,2.3,113.2,-2.2,117.3,1.9,NaN,B. Donovan (27-38),T. Jones (4.2)
1,2024,NBA,Chicago Bulls,39,43,0.476,5th of 5,-1.83,102.8,4.0,114.1,-0.4,115.6,1.1,NaN,B. Donovan (39-43),N. Vučević (7.3)
2,2023,NBA,Chicago Bulls,39,43,0.476,4th of 5,-1.77,96.3,-2.2,114.9,-0.4,116.3,1.0,NaN,B. Donovan (39-43),D. DeRozan (9.2)
3,2022,NBA,Chicago Bulls,40,42,0.488,3rd of 5,1.37,98.5,-0.6,113.5,-1.3,112.2,-2.6,NaN,B. Donovan (40-42),D. DeRozan (8.5)
4,2021,NBA,Chicago Bulls*,46,36,0.561,2nd of 5,-0.38,98.3,0.1,113.2,1.2,113.6,1.6,Lost E. Conf. 1st Rnd.,B. Donovan (46-36),D. DeRozan (8.8)

In [ ]:
# Convert "Finish" to integer by keeping the first letter of string and converting to integer
df["Finish"] = df["Finish"].apply(lambda x: int(x[0]) if isinstance(x, str) else np.nan)
df.head()

,Season,Lg,Team,W,L,W/L%,Finish,SRS,Pace,Rel Pace,ORtg,Rel ORtg,DRtg,Rel DRtg,Playoffs,Coaches,Top WS
0,2025,NBA,Chicago Bulls,27,38,0.415,4,-4.08,101.7,2.3,113.2,-2.2,117.3,1.9,NaN,B. Donovan (27-38),T. Jones (4.2)
1,2024,NBA,Chicago Bulls,39,43,0.476,5,-1.83,102.8,4.0,114.1,-0.4,115.6,1.1,NaN,B. Donovan (39-43),N. Vučević (7.3)
2,2023,NBA,Chicago Bulls,39,43,0.476,4,-1.77,96.3,-2.2,114.9,-0.4,116.3,1.0,NaN,B. Donovan (39-43),D. DeRozan (9.2)
3,2022,NBA,Chicago Bulls,40,42,0.488,3,1.37,98.5,-0.6,113.5,-1.3,112.2,-2.6,NaN,B. Donovan (40-42),D. DeRozan (8.5)
4,2021,NBA,Chicago Bulls*,46,36,0.561,2,-0.38,98.3,0.1,113.2,1.2,113.6,1.6,Lost E. Conf. 1st Rnd.,B. Donovan (46-36),D. DeRozan (8.8)

In [14]:
# drop Lg column, which is always "NBA"
df.drop(columns=["Lg"], inplace=True)
df.head()

,Season,Team,W,L,W/L%,Finish,SRS,Pace,Rel Pace,ORtg,Rel ORtg,DRtg,Rel DRtg,Playoffs,Coaches,Top WS
0,2025,Chicago Bulls,27,38,0.415,4,-4.08,101.7,2.3,113.2,-2.2,117.3,1.9,NaN,B. Donovan (27-38),T. Jones (4.2)
1,2024,Chicago Bulls,39,43,0.476,5,-1.83,102.8,4.0,114.1,-0.4,115.6,1.1,NaN,B. Donovan (39-43),N. Vučević (7.3)
2,2023,Chicago Bulls,39,43,0.476,4,-1.77,96.3,-2.2,114.9,-0.4,116.3,1.0,NaN,B. Donovan (39-43),D. DeRozan (9.2)
3,2022,Chicago Bulls,40,42,0.488,3,1.37,98.5,-0.6,113.5,-1.3,112.2,-2.6,NaN,B. Donovan (40-42),D. DeRozan (8.5)
4,2021,Chicago Bulls*,46,36,0.561,2,-0.38,98.3,0.1,113.2,1.2,113.6,1.6,Lost E. Conf. 1st Rnd.,B. Donovan (46-36),D. DeRozan (8.8)

In [16]:
# rewrite the csv file with the cleaned data
df.to_csv("data/bulls_dataset2.csv", index=False)