# Integrating Datasets
---

## Import cleaned individual datasets

- Dataset 1: Bulls Season Statistics Data
- Dataset 2: Bulls Draft Data

Both datasets were previously cleaned and pushed to our data folder.

In [114]:
import pandas as pd

In [115]:
df1 = pd.read_csv("../data/processed/bulls_season_data.csv")
df1.head()

,Season,Team,W,L,W/L%,Finish,SRS,Pace,Rel Pace,ORtg,Rel ORtg,DRtg,Rel DRtg,Playoffs,Coaches,Top WS
0,2025,Chicago Bulls,27,38,0.415,4,-4.08,101.7,2.3,113.2,-2.2,117.3,1.9,NaN,B. Donovan (27-38),T. Jones (4.2)
1,2024,Chicago Bulls,39,43,0.476,5,-1.83,102.8,4.0,114.1,-0.4,115.6,1.1,NaN,B. Donovan (39-43),N. Vučević (7.3)
2,2023,Chicago Bulls,39,43,0.476,4,-1.77,96.3,-2.2,114.9,-0.4,116.3,1.0,NaN,B. Donovan (39-43),D. DeRozan (9.2)
3,2022,Chicago Bulls,40,42,0.488,3,1.37,98.5,-0.6,113.5,-1.3,112.2,-2.6,NaN,B. Donovan (40-42),D. DeRozan (8.5)
4,2021,Chicago Bulls*,46,36,0.561,2,-0.38,98.3,0.1,113.2,1.2,113.6,1.6,Lost E. Conf. 1st Rnd.,B. Donovan (46-36),D. DeRozan (8.8)

In [116]:
df2 = pd.read_csv("../data/processed/draft_data_cleaned.csv")
df2.head()

,Year,Lg,Rd,Pk,Player,College,Age,Pos,G,GS,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Awards
0,2025,NBA,1,12,Noa Essengue,NaN,19.0,PF,2.0,0.0,...,0.0,0.0,0.0,0.0,0.5,0.0,0.0,0.5,0.0,NaN
1,2024,NBA,1,11,Matas Buzelis,NaN,20.0,SF,80.0,31.0,...,0.7,2.8,3.5,1.0,0.4,0.9,0.9,1.6,8.6,ROY-7
2,2022,NBA,1,18,Dalen Terry,Arizona,20.0,SG,38.0,0.0,...,0.3,0.7,1.0,0.6,0.3,0.1,0.2,0.6,2.2,NaN
3,2021,NBA,2,38,Ayo Dosunmu,Illinois,22.0,SG,77.0,40.0,...,0.4,2.4,2.8,3.3,0.8,0.4,1.4,2.4,8.8,NaN
4,2020,NBA,1,4,Patrick Williams,Florida State,19.0,PF,71.0,71.0,...,0.9,3.7,4.6,1.4,0.9,0.6,1.4,1.8,9.2,NaN

### Merge Datasets 
---

- Left: "Season"
- Right: "Year"

Both columns hold the same information, that being the year of that draft/season. We inner join the two datasets

In [117]:
# Merge the two DataFrames on the 'season'  column for df1, and year for df2
merged_df = pd.merge(df1, df2, left_on='Season', right_on='Year', how='inner')
merged_df.head()

,Season,Team,W,L,W/L%,Finish,SRS,Pace,Rel Pace,ORtg,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Awards
0,2025,Chicago Bulls,27,38,0.415,4,-4.08,101.7,2.3,113.2,...,0.0,0.0,0.0,0.0,0.5,0.0,0.0,0.5,0.0,NaN
1,2024,Chicago Bulls,39,43,0.476,5,-1.83,102.8,4.0,114.1,...,0.7,2.8,3.5,1.0,0.4,0.9,0.9,1.6,8.6,ROY-7
2,2022,Chicago Bulls,40,42,0.488,3,1.37,98.5,-0.6,113.5,...,0.3,0.7,1.0,0.6,0.3,0.1,0.2,0.6,2.2,NaN
3,2021,Chicago Bulls*,46,36,0.561,2,-0.38,98.3,0.1,113.2,...,0.4,2.4,2.8,3.3,0.8,0.4,1.4,2.4,8.8,NaN
4,2020,Chicago Bulls,31,41,0.431,3,-0.94,99.0,-0.2,111.1,...,0.9,3.7,4.6,1.4,0.9,0.6,1.4,1.8,9.2,NaN

We check the columns to ensure all data was correctly integrated

In [118]:
merged_df.columns

Index(['Season', 'Team', 'W', 'L', 'W/L%', 'Finish', 'SRS', 'Pace', 'Rel Pace',
       'ORtg', 'Rel ORtg', 'DRtg', 'Rel DRtg', 'Playoffs', 'Coaches', 'Top WS',
       'Year', 'Lg', 'Rd', 'Pk', 'Player', 'College', 'Age', 'Pos', 'G', 'GS',
       'MP', 'FG', 'FGA', 'FG%', '3P', '3PA', '3P%', '2P', '2PA', '2P%',
       'eFG%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK',
       'TOV', 'PF', 'PTS', 'Awards'],
      dtype='object')

### Missing Values
---

We look at the missing values in the merged dataset to also ensure data was properly integrated. There are columns in which missing values are intentional (playoffs, awards).

In [119]:
merged_df.isnull().sum()

Season       0
Team         0
W            0
L            0
W/L%         0
Finish       0
SRS          0
Pace         0
Rel Pace     0
ORtg         0
Rel ORtg     0
DRtg         0
Rel DRtg     0
Playoffs    26
Coaches      0
Top WS       0
Year         0
Lg           0
Rd           0
Pk           0
Player       0
College      6
Age          4
Pos          4
G            4
GS           4
MP           4
FG           4
FGA          4
FG%          4
3P           4
3PA          4
3P%          9
2P           4
2PA          4
2P%          4
eFG%         4
FT           4
FTA          4
FT%          6
ORB          4
DRB          4
TRB          4
AST          4
STL          4
BLK          4
TOV          4
PF           4
PTS          4
Awards      33
dtype: int64

We see that there are four missing values across Age, Pos, G; mostly columns from the draft dataset. We'll explore what observations are missing

In [120]:
merged_df[merged_df['Age'].isnull()]["Player"]

5     Marko Simonovic
23      JamesOn Curry
27       Mario Austin
28        Tommy Smith
Name: Player, dtype: object

Let's check the draft dataset to see if these were missing in the second dataset

In [121]:
# check if missing ages are missing in dataset "df2"
df2[df2["Player"].isin(merged_df[merged_df['Age'].isnull()]["Player"])]

,Year,Lg,Rd,Pk,Player,College,Age,Pos,G,GS,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Awards
5,2020,NBA,2,44,Marko Simonovic,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,2007,NBA,2,51,JamesOn Curry,Oklahoma State,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,2003,NBA,2,36,Mario Austin,Mississippi State,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,2003,NBA,2,53,Tommy Smith,Arizona State,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

We find that these values are missing. When we check ESPN for each of their stats, the reason these are missing is because they did not play in their rookie season. This should not take away from "Age" or "Position" so we will have to manually fill these out in our merged df.

In [122]:
merged_df["Pos"].unique()

array(['PF', 'SF', 'SG', nan, 'PG', 'C'], dtype=object)

In [123]:
merged_df.loc[merged_df['Player'] == 'Marko Simonovic', 'Age'] = 21
merged_df.loc[merged_df['Player'] == 'Marko Simonovic', 'Pos'] = 'C'

merged_df.loc[merged_df['Player'] == 'JamesOn Curry', 'Age'] = 22
merged_df.loc[merged_df['Player'] == 'JamesOn Curry', 'Pos'] = 'PG'

merged_df.loc[merged_df['Player'] == 'Mario Austin', 'Age'] = 21
merged_df.loc[merged_df['Player'] == 'Mario Austin', 'Pos'] = 'SF'

merged_df.loc[merged_df['Player'] == 'Tommy Smith', 'Age'] = 23
merged_df.loc[merged_df['Player'] == 'Tommy Smith', 'Pos'] = 'SF'

For the rest of the player stats, if missing, we can fill in with a zero.

In [124]:
cols_to_fill = ['G', 'GS','MP', 'FG', 'FGA', 'FG%', '3P', '3PA', '3P%', '2P', '2PA', '2P%',
       'eFG%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK',
       'TOV', 'PF', 'PTS']
merged_df[cols_to_fill] = merged_df[cols_to_fill].fillna(0)

In [125]:
merged_df.head()

,Season,Team,W,L,W/L%,Finish,SRS,Pace,Rel Pace,ORtg,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Awards
0,2025,Chicago Bulls,27,38,0.415,4,-4.08,101.7,2.3,113.2,...,0.0,0.0,0.0,0.0,0.5,0.0,0.0,0.5,0.0,NaN
1,2024,Chicago Bulls,39,43,0.476,5,-1.83,102.8,4.0,114.1,...,0.7,2.8,3.5,1.0,0.4,0.9,0.9,1.6,8.6,ROY-7
2,2022,Chicago Bulls,40,42,0.488,3,1.37,98.5,-0.6,113.5,...,0.3,0.7,1.0,0.6,0.3,0.1,0.2,0.6,2.2,NaN
3,2021,Chicago Bulls*,46,36,0.561,2,-0.38,98.3,0.1,113.2,...,0.4,2.4,2.8,3.3,0.8,0.4,1.4,2.4,8.8,NaN
4,2020,Chicago Bulls,31,41,0.431,3,-0.94,99.0,-0.2,111.1,...,0.9,3.7,4.6,1.4,0.9,0.6,1.4,1.8,9.2,NaN

Finally, we can replace missing values in "Playoffs" and "Awards" with a simple value like "None" to indicate that there was no playoff appearance or awards won for that player.

In [126]:
# check unique values for playoffs
merged_df["Playoffs"].unique()

array([nan, 'Lost E. Conf. 1st Rnd.', 'Lost E. Conf. Semis'], dtype=object)

In [127]:
merged_df["Playoffs"] = merged_df["Playoffs"].fillna("Missed Playoffs")

In [128]:
# check unique values for awards
merged_df["Awards"].unique()

array([nan, 'ROY-7', 'ROY-5', 'ROY-1', 'ROY-2,6MOY-1', 'ROY-4'],
      dtype=object)

If we want to gain more information about player awards, we can create a column for "ROY" whith the numeric value of their ranking in voting for the element. We have one player that won "sixth man of the year" or "6MOY" in the code, but since we only have one occurence we wouldn't have enough evidence to suggest the effect of winning sixth man of the year.

In [129]:
def extract_roy_rank(awards):
    if pd.isnull(awards):
        return 0
    # extract the first 5 characters of the awards string
    awards_prefix = awards[:5]
    # extract the last character of the awards string
    awards_suffix = awards_prefix[-1]
    # place suffix into column "ROY"
    if awards_prefix.startswith("ROY-") and awards_suffix.isdigit():
        return int(awards_suffix)
    else:        
        return 0

merged_df["ROY"] = merged_df["Awards"].apply(extract_roy_rank)
merged_df

,Season,Team,W,L,W/L%,Finish,SRS,Pace,Rel Pace,ORtg,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Awards,ROY
0,2025,Chicago Bulls,27,38,0.415,4,-4.08,101.7,2.3,113.2,...,0.0,0.0,0.0,0.5,0.0,0.0,0.5,0.0,NaN,0
1,2024,Chicago Bulls,39,43,0.476,5,-1.83,102.8,4.0,114.1,...,2.8,3.5,1.0,0.4,0.9,0.9,1.6,8.6,ROY-7,7
2,2022,Chicago Bulls,40,42,0.488,3,1.37,98.5,-0.6,113.5,...,0.7,1.0,0.6,0.3,0.1,0.2,0.6,2.2,NaN,0
3,2021,Chicago Bulls*,46,36,0.561,2,-0.38,98.3,0.1,113.2,...,2.4,2.8,3.3,0.8,0.4,1.4,2.4,8.8,NaN,0
4,2020,Chicago Bulls,31,41,0.431,3,-0.94,99.0,-0.2,111.1,...,3.7,4.6,1.4,0.9,0.6,1.4,1.8,9.2,NaN,0
5,2020,Chicago Bulls,31,41,0.431,3,-0.94,99.0,-0.2,111.1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0
6,2019,Chicago Bulls,22,43,0.338,3,-4.00,99.7,-0.6,106.7,...,3.1,3.5,2.7,0.8,0.1,1.7,1.8,13.2,ROY-5,5
7,2019,Chicago Bulls,22,43,0.338,3,-4.00,99.7,-0.6,106.7,...,1.3,2.5,0.5,0.3,1.3,0.7,2.3,5.1,NaN,0
8,2018,Chicago Bulls,22,60,0.268,4,-8.32,99.0,-1.0,104.8,...,5.0,7.0,1.8,0.6,1.3,1.5,3.5,10.3,NaN,0
9,2018,Chicago Bulls,22,60,0.268,4,-8.32,99.0,-1.0,104.8,...,3.5,4.2,0.8,0.5,0.1,0.6,1.3,5.2,NaN,0
10,2016,Chicago Bulls*,41,41,0.500,4,0.03,95.3,-1.1,107.4,...,2.5,2.6,1.1,0.5,0.1,0.9,1.5,5.1,NaN,0
11,2016,Chicago Bulls*,41,41,0.500,4,0.03,95.3,-1.1,107.4,...,2.5,2.8,0.8,0.3,0.4,0.9,1.8,5.5,NaN,0
12,2015,Chicago Bulls,42,40,0.512,4,-1.46,95.7,-0.1,105.0,...,3.5,5.4,0.8,0.4,0.4,0.9,1.6,7.0,NaN,0
13,2014,Chicago Bulls*,50,32,0.610,2,2.54,92.8,-1.1,107.5,...,0.1,0.4,0.1,0.1,0.1,0.2,0.4,0.6,NaN,0
14,2013,Chicago Bulls*,48,34,0.585,2,1.20,90.2,-3.7,102.5,...,1.4,1.6,0.9,0.4,0.2,0.6,1.1,4.5,NaN,0
15,2013,Chicago Bulls*,48,34,0.585,2,1.20,90.2,-3.7,102.5,...,0.3,0.3,0.1,0.0,0.2,0.1,0.3,0.3,NaN,0
16,2012,Chicago Bulls*,45,37,0.549,2,-0.02,89.3,-2.7,103.5,...,0.9,0.9,1.3,0.2,0.1,0.7,1.0,2.1,NaN,0
17,2011,Chicago Bulls*,50,16,0.758,1,7.43,89.1,-2.2,107.4,...,0.8,1.3,0.3,0.3,0.1,0.3,0.5,2.6,NaN,0
18,2009,Chicago Bulls*,41,41,0.500,3,-1.64,93.1,0.4,103.5,...,1.4,2.0,0.7,0.3,0.7,1.0,1.9,3.9,NaN,0
19,2009,Chicago Bulls*,41,41,0.500,3,-1.64,93.1,0.4,103.5,...,4.7,7.5,0.9,0.6,1.3,1.4,3.4,9.0,ROY-5,5
20,2008,Chicago Bulls*,41,41,0.500,2,-0.16,93.1,1.4,108.4,...,2.7,3.9,6.3,0.8,0.2,2.5,1.5,16.8,ROY-1,1
21,2007,Chicago Bulls,33,49,0.402,4,-3.19,93.0,0.6,103.9,...,3.3,5.6,1.1,0.9,0.9,1.2,2.3,6.6,NaN,0
22,2007,Chicago Bulls,33,49,0.402,4,-3.19,93.0,0.6,103.9,...,1.6,2.8,0.7,0.3,0.3,0.9,1.9,4.3,NaN,0
23,2007,Chicago Bulls,33,49,0.402,4,-3.19,93.0,0.6,103.9,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0
24,2004,Chicago Bulls*,47,35,0.573,2,0.65,92.4,1.5,101.4,...,2.0,2.6,2.0,0.6,0.1,2.3,2.7,15.1,"ROY-2,6MOY-1",2
25,2004,Chicago Bulls*,47,35,0.573,2,0.65,92.4,1.5,101.4,...,2.3,2.6,4.9,1.0,0.0,1.5,2.5,5.9,NaN,0
26,2003,Chicago Bulls,23,59,0.280,8,-6.69,92.2,2.1,96.6,...,2.9,3.4,6.8,1.3,0.3,2.7,3.6,12.0,ROY-4,4
27,2003,Chicago Bulls,23,59,0.280,8,-6.69,92.2,2.1,96.6,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0
28,2003,Chicago Bulls,23,59,0.280,8,-6.69,92.2,2.1,96.6,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0
29,2002,Chicago Bulls,30,52,0.366,6,-5.31,93.5,2.5,100.2,...,1.3,2.1,0.3,0.2,0.1,0.8,1.8,3.5,NaN,0
30,2002,Chicago Bulls,30,52,0.366,6,-5.31,93.5,2.5,100.2,...,0.6,0.7,0.7,0.2,0.0,0.3,1.2,1.8,NaN,0
31,2002,Chicago Bulls,30,52,0.366,6,-5.31,93.5,2.5,100.2,...,1.8,3.0,0.3,0.2,0.4,0.8,2.5,4.8,NaN,0
32,2001,Chicago Bulls,21,61,0.256,8,-8.52,90.5,-0.2,98.2,...,2.2,3.8,0.3,0.2,0.7,1.0,2.4,6.7,NaN,0
33,2001,Chicago Bulls,21,61,0.256,8,-8.52,90.5,-0.2,98.2,...,2.4,3.3,2.2,0.7,0.6,1.3,2.4,8.7,NaN,0
34,2000,Chicago Bulls,15,67,0.183,8,-9.09,89.3,-2.0,97.2,...,3.3,4.3,1.1,0.4,0.3,1.7,2.4,9.5,NaN,0
35,2000,Chicago Bulls,15,67,0.183,8,-9.09,89.3,-2.0,97.2,...,1.0,1.6,0.3,0.3,0.5,0.6,1.3,1.3,NaN,0
36,2000,Chicago Bulls,15,67,0.183,8,-9.09,89.3,-2.0,97.2,...,0.8,1.1,1.9,0.3,0.2,0.7,1.1,6.0,NaN,0
37,2000,Chicago Bulls,15,67,0.183,8,-9.09,89.3,-2.0,97.2,...,1.4,2.1,0.3,0.3,0.4,0.8,2.4,1.9,NaN,0
38,2000,Chicago Bulls,15,67,0.183,8,-9.09,89.3,-2.0,97.2,...,1.2,1.6,2.9,1.0,0.0,1.1,2.0,6.3,NaN,0

In [130]:
# ensure that if awards contains "ROY", ROY column contains correct rank
merged_df[merged_df["Awards"].str.contains("ROY", na=False)][["Player", "Awards", "ROY"]]

           Player        Awards  ROY
1   Matas Buzelis         ROY-7    7
6      Coby White         ROY-5    5
19     Taj Gibson         ROY-5    5
20   Derrick Rose         ROY-1    1
24     Ben Gordon  ROY-2,6MOY-1    2
26   Kirk Hinrich         ROY-4    4

Now we can fill the awards column, if Nan, with "None"

In [131]:
merged_df["Awards"] = merged_df["Awards"].fillna("None")

In [132]:
merged_df

,Season,Team,W,L,W/L%,Finish,SRS,Pace,Rel Pace,ORtg,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Awards,ROY
0,2025,Chicago Bulls,27,38,0.415,4,-4.08,101.7,2.3,113.2,...,0.0,0.0,0.0,0.5,0.0,0.0,0.5,0.0,None,0
1,2024,Chicago Bulls,39,43,0.476,5,-1.83,102.8,4.0,114.1,...,2.8,3.5,1.0,0.4,0.9,0.9,1.6,8.6,ROY-7,7
2,2022,Chicago Bulls,40,42,0.488,3,1.37,98.5,-0.6,113.5,...,0.7,1.0,0.6,0.3,0.1,0.2,0.6,2.2,None,0
3,2021,Chicago Bulls*,46,36,0.561,2,-0.38,98.3,0.1,113.2,...,2.4,2.8,3.3,0.8,0.4,1.4,2.4,8.8,None,0
4,2020,Chicago Bulls,31,41,0.431,3,-0.94,99.0,-0.2,111.1,...,3.7,4.6,1.4,0.9,0.6,1.4,1.8,9.2,None,0
5,2020,Chicago Bulls,31,41,0.431,3,-0.94,99.0,-0.2,111.1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,None,0
6,2019,Chicago Bulls,22,43,0.338,3,-4.00,99.7,-0.6,106.7,...,3.1,3.5,2.7,0.8,0.1,1.7,1.8,13.2,ROY-5,5
7,2019,Chicago Bulls,22,43,0.338,3,-4.00,99.7,-0.6,106.7,...,1.3,2.5,0.5,0.3,1.3,0.7,2.3,5.1,None,0
8,2018,Chicago Bulls,22,60,0.268,4,-8.32,99.0,-1.0,104.8,...,5.0,7.0,1.8,0.6,1.3,1.5,3.5,10.3,None,0
9,2018,Chicago Bulls,22,60,0.268,4,-8.32,99.0,-1.0,104.8,...,3.5,4.2,0.8,0.5,0.1,0.6,1.3,5.2,None,0
10,2016,Chicago Bulls*,41,41,0.500,4,0.03,95.3,-1.1,107.4,...,2.5,2.6,1.1,0.5,0.1,0.9,1.5,5.1,None,0
11,2016,Chicago Bulls*,41,41,0.500,4,0.03,95.3,-1.1,107.4,...,2.5,2.8,0.8,0.3,0.4,0.9,1.8,5.5,None,0
12,2015,Chicago Bulls,42,40,0.512,4,-1.46,95.7,-0.1,105.0,...,3.5,5.4,0.8,0.4,0.4,0.9,1.6,7.0,None,0
13,2014,Chicago Bulls*,50,32,0.610,2,2.54,92.8,-1.1,107.5,...,0.1,0.4,0.1,0.1,0.1,0.2,0.4,0.6,None,0
14,2013,Chicago Bulls*,48,34,0.585,2,1.20,90.2,-3.7,102.5,...,1.4,1.6,0.9,0.4,0.2,0.6,1.1,4.5,None,0
15,2013,Chicago Bulls*,48,34,0.585,2,1.20,90.2,-3.7,102.5,...,0.3,0.3,0.1,0.0,0.2,0.1,0.3,0.3,None,0
16,2012,Chicago Bulls*,45,37,0.549,2,-0.02,89.3,-2.7,103.5,...,0.9,0.9,1.3,0.2,0.1,0.7,1.0,2.1,None,0
17,2011,Chicago Bulls*,50,16,0.758,1,7.43,89.1,-2.2,107.4,...,0.8,1.3,0.3,0.3,0.1,0.3,0.5,2.6,None,0
18,2009,Chicago Bulls*,41,41,0.500,3,-1.64,93.1,0.4,103.5,...,1.4,2.0,0.7,0.3,0.7,1.0,1.9,3.9,None,0
19,2009,Chicago Bulls*,41,41,0.500,3,-1.64,93.1,0.4,103.5,...,4.7,7.5,0.9,0.6,1.3,1.4,3.4,9.0,ROY-5,5
20,2008,Chicago Bulls*,41,41,0.500,2,-0.16,93.1,1.4,108.4,...,2.7,3.9,6.3,0.8,0.2,2.5,1.5,16.8,ROY-1,1
21,2007,Chicago Bulls,33,49,0.402,4,-3.19,93.0,0.6,103.9,...,3.3,5.6,1.1,0.9,0.9,1.2,2.3,6.6,None,0
22,2007,Chicago Bulls,33,49,0.402,4,-3.19,93.0,0.6,103.9,...,1.6,2.8,0.7,0.3,0.3,0.9,1.9,4.3,None,0
23,2007,Chicago Bulls,33,49,0.402,4,-3.19,93.0,0.6,103.9,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,None,0
24,2004,Chicago Bulls*,47,35,0.573,2,0.65,92.4,1.5,101.4,...,2.0,2.6,2.0,0.6,0.1,2.3,2.7,15.1,"ROY-2,6MOY-1",2
25,2004,Chicago Bulls*,47,35,0.573,2,0.65,92.4,1.5,101.4,...,2.3,2.6,4.9,1.0,0.0,1.5,2.5,5.9,None,0
26,2003,Chicago Bulls,23,59,0.280,8,-6.69,92.2,2.1,96.6,...,2.9,3.4,6.8,1.3,0.3,2.7,3.6,12.0,ROY-4,4
27,2003,Chicago Bulls,23,59,0.280,8,-6.69,92.2,2.1,96.6,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,None,0
28,2003,Chicago Bulls,23,59,0.280,8,-6.69,92.2,2.1,96.6,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,None,0
29,2002,Chicago Bulls,30,52,0.366,6,-5.31,93.5,2.5,100.2,...,1.3,2.1,0.3,0.2,0.1,0.8,1.8,3.5,None,0
30,2002,Chicago Bulls,30,52,0.366,6,-5.31,93.5,2.5,100.2,...,0.6,0.7,0.7,0.2,0.0,0.3,1.2,1.8,None,0
31,2002,Chicago Bulls,30,52,0.366,6,-5.31,93.5,2.5,100.2,...,1.8,3.0,0.3,0.2,0.4,0.8,2.5,4.8,None,0
32,2001,Chicago Bulls,21,61,0.256,8,-8.52,90.5,-0.2,98.2,...,2.2,3.8,0.3,0.2,0.7,1.0,2.4,6.7,None,0
33,2001,Chicago Bulls,21,61,0.256,8,-8.52,90.5,-0.2,98.2,...,2.4,3.3,2.2,0.7,0.6,1.3,2.4,8.7,None,0
34,2000,Chicago Bulls,15,67,0.183,8,-9.09,89.3,-2.0,97.2,...,3.3,4.3,1.1,0.4,0.3,1.7,2.4,9.5,None,0
35,2000,Chicago Bulls,15,67,0.183,8,-9.09,89.3,-2.0,97.2,...,1.0,1.6,0.3,0.3,0.5,0.6,1.3,1.3,None,0
36,2000,Chicago Bulls,15,67,0.183,8,-9.09,89.3,-2.0,97.2,...,0.8,1.1,1.9,0.3,0.2,0.7,1.1,6.0,None,0
37,2000,Chicago Bulls,15,67,0.183,8,-9.09,89.3,-2.0,97.2,...,1.4,2.1,0.3,0.3,0.4,0.8,2.4,1.9,None,0
38,2000,Chicago Bulls,15,67,0.183,8,-9.09,89.3,-2.0,97.2,...,1.2,1.6,2.9,1.0,0.0,1.1,2.0,6.3,None,0

We now have a fully cleaned merged datset. To reiterate the steps we took:

- We imported both Chicago Bulls season & draft datasets
- We inner joined the datasets on the "season/year" column
- We cleaned missing values
    - We hard-coded missing Age/Pos for players that did not play their rookie season
    - We replaced missing values with zeros for those players
    - We filled missing playoffs/awards with "Missed" or "None"
- We extracted Rookie Of The Year ranking for the player

We can finally upload this dataset to the data folder in github.

In [ ]:
write_csv_path = "../data/processed/final_bulls_data.csv"
merged_df.to_csv(write_csv_path, index=False)